version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: netflix-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: netflix
      POSTGRES_PASSWORD: netflix123
      POSTGRES_DB: netflix_identity
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - netflix-network

  redis:
    image: redis:7-alpine
    container_name: netflix-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - netflix-network

volumes:
  postgres_data:
  redis_data:

networks:
  netflix-network:
    driver: bridge